[build]
dockerfilePath = "Dockerfile.prod"

[deploy]
startCommand = "/entrypoint.sh"
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 60
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
